In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5711, 289, 6810, 1801],
 [5711, 289, 6810, 840],
 [5711, 9657, 6810, 20],
 [3528, 7385, 4230, 2298, 9705],
 [3528, 7385, 4230, 2298, 7994],
 [1504, 5711, 3108, 6810, 5438],
 [1891, 828, 8726, 2298]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5711  289 6810 1801]
 [   0    0    0    0 5711  289 6810  840]
 [   0    0    0    0 5711 9657 6810   20]
 [   0    0    0 3528 7385 4230 2298 9705]
 [   0    0    0 3528 7385 4230 2298 7994]
 [   0    0    0 1504 5711 3108 6810 5438]
 [   0    0    0    0 1891  828 8726 2298]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 408ms/step


array([[[-8.89134407e-03, -1.42732970e-02, -4.74972241e-02,
          4.95201014e-02, -7.70150498e-03, -1.38436072e-02,
          3.17619778e-02, -3.65764871e-02,  7.55013153e-03,
         -3.57067101e-02],
        [-8.89134407e-03, -1.42732970e-02, -4.74972241e-02,
          4.95201014e-02, -7.70150498e-03, -1.38436072e-02,
          3.17619778e-02, -3.65764871e-02,  7.55013153e-03,
         -3.57067101e-02],
        [-8.89134407e-03, -1.42732970e-02, -4.74972241e-02,
          4.95201014e-02, -7.70150498e-03, -1.38436072e-02,
          3.17619778e-02, -3.65764871e-02,  7.55013153e-03,
         -3.57067101e-02],
        [-8.89134407e-03, -1.42732970e-02, -4.74972241e-02,
          4.95201014e-02, -7.70150498e-03, -1.38436072e-02,
          3.17619778e-02, -3.65764871e-02,  7.55013153e-03,
         -3.57067101e-02],
        [ 9.65356827e-04,  6.82734326e-03,  2.42389925e-02,
          4.33350727e-03,  3.91106494e-02,  4.71619256e-02,
          3.61311100e-02,  3.16782854e-02, -1.346335

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 5711,  289, 6810, 1801])

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 81ms/step


array([[-0.00889134, -0.0142733 , -0.04749722,  0.0495201 , -0.0077015 ,
        -0.01384361,  0.03176198, -0.03657649,  0.00755013, -0.03570671],
       [-0.00889134, -0.0142733 , -0.04749722,  0.0495201 , -0.0077015 ,
        -0.01384361,  0.03176198, -0.03657649,  0.00755013, -0.03570671],
       [-0.00889134, -0.0142733 , -0.04749722,  0.0495201 , -0.0077015 ,
        -0.01384361,  0.03176198, -0.03657649,  0.00755013, -0.03570671],
       [-0.00889134, -0.0142733 , -0.04749722,  0.0495201 , -0.0077015 ,
        -0.01384361,  0.03176198, -0.03657649,  0.00755013, -0.03570671],
       [ 0.00096536,  0.00682734,  0.02423899,  0.00433351,  0.03911065,
         0.04716193,  0.03613111,  0.03167829, -0.01346336, -0.03966688],
       [-0.04355932, -0.03685719, -0.01455363,  0.0148731 , -0.01349229,
         0.02120246, -0.04618567, -0.00219188, -0.03597683,  0.0013808 ],
       [-0.02603821,  0.00500762,  0.03541485,  0.01130996, -0.02415694,
        -0.00038232, -0.01637642, -0.00868903